# -*- coding: utf-8 -*-
"""HHA 507 PROJECT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-chQYPCnl8YJ9qmeoX-GyIGVa6KszbWf
"""

!pip install pymysql sqlalchemy python-dotenv

!git clone https://github.com/aimachaudhry/507_groupproject_2025.git
!ls 507_groupproject_2025

DB_HOST='shtm-fallprev.mysql.database.azure.com'
DB_USER='ahistudent'
DB_PASSWORD='researcher'
DB_NAME='sbu_athletics'
DB_TABLE='research_experiment_refactor_test'

!python 507_groupproject_2025/part2_cleaning.py

import sys
sys.path.append('/content/507_groupproject_2025')

import part2_cleaning as p2

df = p2.df
selected_metrics = p2.selected_metrics

df.head()

# 2.3 Derived Metric in Colab
import pandas as pd
from scipy.stats import zscore

print("\n=== 2.3 Derived Metric: Team Means & Relative Performance ===")

# 2.3a — Calculate team mean for each metric
team_metric_means = (
    df.groupby(["metric", "team"])["value"]
      .mean()
      .reset_index(name="team_mean")
)

# Merge into full dataset
df_derived = df.merge(team_metric_means, on=["metric", "team"], how="left")

# 2.3b — Percent difference from team mean
df_derived["percent_diff"] = (
    (df_derived["value"] - df_derived["team_mean"]) / df_derived["team_mean"]
) * 100

# 2.3c — Z-scores
df_derived["z_score"] = (
    df_derived.groupby(["metric", "team"])["value"].transform(zscore)
)

# 2.3d — Top 5 and Bottom 5 Performers
top_bottom_records = []

for metric_name in selected_metrics:
    metric_data = df_derived[df_derived["metric"] == metric_name].copy()

    if metric_data.empty:
        print(f"\n⚠️ No data available for: {metric_name}")
        continue

    top5 = metric_data.sort_values("percent_diff", ascending=False).head(5)
    bottom5 = metric_data.sort_values("percent_diff", ascending=True).head(5)

    print(f"\n--- Metric: {metric_name} ---")
    print("Top 5 performers:")
    display(top5[["playername", "team", "value", "team_mean", "percent_diff","z_score"]])

    print("Bottom 5 performers:")
    display(bottom5[["playername", "team", "value", "team_mean", "percent_diff","z_score"]])

    top_bottom_records.append(top5)
    top_bottom_records.append(bottom5)

# 2.3e — Save results
if top_bottom_records:
    top_bottom_df = pd.concat(top_bottom_records, ignore_index=True)

    df_derived.to_csv("part2_derived_metrics_full.csv", index=False)
    top_bottom_df.to_csv("part2_top_bottom_performers.csv", index=False)

    print("\nSaved part2_derived_metrics_full.csv")
    print("Saved part2_top_bottom_performers.csv")

from google.colab import files

files.download("part2_derived_metrics_full.csv")
files.download("part2_top_bottom_performers.csv")